require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gemspec|
    gemspec.name = "pdf-my-url"
    gemspec.summary = "A basic ruby-on-rails interface to http://pdfmyurl.com/"
    gemspec.homepage = "http://github.com/ksylvest/pdf-my-url"
    gemspec.author = "Kevin Sylvestre"
  end
rescue LoadError
  puts "Jeweler not available. Install it with: gem install jeweler"
end